# Generated by Django 4.1 on 2023-12-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logged_in_as_seller',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
